In [1]:
import cv2

In [2]:
import numpy as np

In [39]:
canvas = np.zeros((512,512,3), dtype = np.uint8) # 512 512 boyutunda siyah bir ekran

In [40]:
cv2.imshow("Canvas", canvas)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [41]:
# rengini değiştirmek istersek 

In [42]:
beyazcanvas = np.zeros((512,512,3), dtype = np.uint8) + 255

In [43]:
cv2.imshow("Canvas", beyazcanvas)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [44]:
img = np.zeros((10,10,3), np.uint8)
cv2.imshow("Canvas", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [45]:
# PİKSELLERİ RENKLENDİRME 
img[0,0] = (255,255,255)
img[0,1] = (255,255,200)
img[0,2] = (255,255,100)
img[0,3] = (255,255,15)


In [46]:
#YENİDEN BOYUTLANDIRMAK İÇİN RESİZE FONK KULLANDIK
img = cv2.resize(img,(1000,1000), interpolation = cv2.INTER_AREA)

In [47]:
cv2.imshow("Renkli Img", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

#### Siyah Beyaz görüntü oluşturalım

In [14]:
import numpy as np
import cv2

img = np.zeros((300, 300), np.uint8)
img[0, 0] = 255
img[0, 1] = 200
img[0, 2] = 100
img[0, 3] = 15
img[200, 200] = 200
cv2.imshow("Canvas", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

# renkler baya küçük alanda yer kaplıyor bu yüzden gözükmeyebilr

### Çizim Fonksiyonları

In [1]:
import numpy as np 
import cv2

In [3]:
canvas = np.zeros((512,512,3), np.uint8) + 255

### Doğru Çizimi

In [12]:
cv2.line(canvas,(50,50),(512,512),(255,0,0),thickness = 5) #baslangıç noktası (50,50) bitiş noktası (512,512) ve rengimiz (255,0,0) kalınlık ise thickness

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255,   0,   0],
        [255,   0,   0],
        [255,   0,   0]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255,   0,   0],
        [255,   0,   0],
        [255,   0,   0]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255,   0,   0],
        [255,   0,   0],
        [255,   0,   0]]

In [13]:
cv2.line(canvas,(150,50),(202,202),(255,123,130),thickness = 11)

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255,   0,   0],
        [255,   0,   0],
        [255,   0,   0]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255,   0,   0],
        [255,   0,   0],
        [255,   0,   0]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255,   0,   0],
        [255,   0,   0],
        [255,   0,   0]]

### Dikdörtgen Çizimi

In [15]:
cv2.rectangle(canvas,(20,20),(50,50),(0,255,0), thickness = -1) # dikdörtgenin sol üst köşesi (20,20) sağ alt köşesi (50,50) kalınlığı -1 verdiğimizde içi dolu bir dikdörtgen elde ediyoruz

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255,   0,   0],
        [255,   0,   0],
        [255,   0,   0]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255,   0,   0],
        [255,   0,   0],
        [255,   0,   0]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255,   0,   0],
        [255,   0,   0],
        [255,   0,   0]]

### Çember Çizimi

In [19]:
cv2.circle(canvas,(250,250),100,(0,0,255), thickness = -1) # (canvas,merkez koordinatı, yarıçapı, renk, kalınlık)

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255,   0,   0],
        [255,   0,   0],
        [255,   0,   0]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255,   0,   0],
        [255,   0,   0],
        [255,   0,   0]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255,   0,   0],
        [255,   0,   0],
        [255,   0,   0]]

### Üçgen çizimi

In [21]:
# Üçgen için ayrı bır hazır fonksiyon yok bu yuzden doğruları kullanarak üçgen oluşturabiliriz

In [30]:
p1 = (100,200)
p2 = (50,50)
p3 = (300,100)

In [31]:
cv2.line(canvas,p1,p2,(0,0,0),4)
cv2.line(canvas,p2,p3,(0,0,0),4)
cv2.line(canvas,p1,p3,(0,0,0),4)

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255,   0,   0],
        [255,   0,   0],
        [255,   0,   0]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255,   0,   0],
        [255,   0,   0],
        [255,   0,   0]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255,   0,   0],
        [255,   0,   0],
        [255,   0,   0]]

### Herhangi bir Şekil Oluşturma

In [34]:
points = np.array([[[110,200],[330,200],[290,220],[120,250]]], np.int32)

In [35]:
cv2.polylines(canvas, [points],True,(0,0,100),5) # şeklin kapalı olması için True dedik

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255,   0,   0],
        [255,   0,   0],
        [255,   0,   0]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255,   0,   0],
        [255,   0,   0],
        [255,   0,   0]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255,   0,   0],
        [255,   0,   0],
        [255,   0,   0]]

### Elips Çizimi

In [37]:
cv2.ellipse(canvas,(300,300),(80,20),10, 90,360, (255,255,0), -1)

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255,   0,   0],
        [255,   0,   0],
        [255,   0,   0]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255,   0,   0],
        [255,   0,   0],
        [255,   0,   0]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255,   0,   0],
        [255,   0,   0],
        [255,   0,   0]]

In [39]:
# ellipse ( (merkez noktası), ( genişlik,yukseklık),yatay eksenle yapıcagı açı,başlangiç açısı, bitiş açısı, renk, kalınlık)

In [38]:
cv2.imshow("Canvas",canvas)
cv2.waitKey(0)
cv2.destroyAllWindows()